### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by emreb** [rogy/smr-challenge#1]
Are we planning to update the README with instructions on how ot run this?

Is it by design that it does not like my just fires name and email? Maybe we should qualify the name field.

**Comment by rogy** [comment]
Yes I'll update the README tonight and will add better validation to the fields.

**Comment by rogy** [comment]
Updated @emreb

**Comment by emreb** [comment]
Potential alternatives to add , run node.js serve or python SimpleHTTPServer

**Comment by emreb** [comment]
Cheers
