### ISSUE TITLE
Challenge 3

### ISSUE THREAD

**Issue by emreb** [rogy/smr-challenge#10]
Further clarification needed.

1) why do you need it as integer, the angle can be a decimal 
2) are you looking for the short angle or the long angle.

**Comment by emreb** [comment]
BTW: What do you check for, bc the irght function/formula is

Math.floor(Math.abs((hours*60-11*minutes)/2));

**Comment by emreb** [comment]
Math.floor(Math.abs((hours x 60-11 x minutes)/2));

**Comment by emreb** [comment]
I just looked at the answer
smr-challenge/js/answers/3.js

is definitely wrong. first of all, the hour hand moves 6 degress for every minute.

The right answer is calculated by the function
Math.floor(Math.abs((hours * 60 - 11 * minutes)/2));

Please correct.

**Comment by rogy** [comment]
I should have checked robs logic!

Amended

**Comment by emreb** [comment]
But you gave test cases right? There are many other ways of calculating.
But this would give the right answer.

**Comment by rogy** [comment]
Yeah it runs a test to see if the persons code gives the correct answer

**Comment by emreb** [comment]
You shoudl check few different cases,
Where are these tests?

**Comment by roberttod** [comment]
Let's say you want the short angle. The full code looks like this (without factorisation). Probably too late to help now but I wanted to fix this.

```javascript
function handAngle (hours, minutes) {
  var minutesAngle = (minutes / 60) * 360
  var hoursAngle = (hours / 12) * 360 + (minutes / 60) * (360 / 12)
  var minutesHoursAngle = Math.abs(hoursAngle - minutesAngle)
  return minutesHoursAngle > 180 ? 360 - minutesHoursAngle : minutesHoursAngle
}
```

**Comment by emreb** [comment]
For a 24 hour clock the answer is this.

```
return  Math.abs((hours * 60 - 11 * minutes)/2) % 360;
```

However, we should have some unit tests to make sure all the answers submitted can be properly evaluated.

**Comment by roberttod** [comment]
If you want the short angle you need to do `minutesHoursAngle > 180 ? 360 - minutesHoursAngle : minutesHoursAngle`. If this isn't used then e.g. `handAngle(9, 15)` returns `187.5`. This should be `172.5`.

For 24 hour time
```javascript
function handAngle (hours, minutes) {
  var minutesAngle = (minutes / 60) * 360
  var hoursAngle = (hours / 12) * 360 + (minutes / 60) * (360 / 12)
  var minutesHoursAngle = Math.abs(hoursAngle - minutesAngle) % 360
  return minutesHoursAngle > 180 ? 360 - minutesHoursAngle : minutesHoursAngle
}
```

I agree; we need unit tests for this.

**Comment by emreb** [comment]
Thanks to @davidpadbury This is now done.
