### ISSUE TITLE
Timing

### ISSUE THREAD

**Issue by roberttod** [rogy/smr-challenge#2]
The time is in deciseconds not milliseconds... which is an odd measurement.

```javascript
setInterval(function () {
  msTime++;
}, 100);
```

Also, never time in js using `setTimeout` or `setInterval`, both are very inaccurate. Instead do something like

```javascript
var startTime = Date.now();
// Do stuff
var timeSinceStart = Date.now() - startTime;
```

**Comment by rogy** [comment]
Solved
